import express from 'express';
import PDFDocument from 'pdfkit';
import nodemailer from 'nodemailer';
import twilio from 'twilio';
import { authenticate } from '../middleware/auth.js';
import { config } from '../config/config.js';
import Note from '../models/Note.js';

const router = express.Router();

/**
 * @route   POST /output/pdf
 * @desc    Generate PDF from notes
 * @access  Private
 */
router.post('/pdf', authenticate, async (req, res, next) => {
  try {
    const { note_id, title, content } = req.body;

    let noteTitle = title;
    let noteContent = content;

    // If note_id provided, fetch from database
    if (note_id) {
      const note = await Note.findOne({
        _id: note_id,
        user_id: req.user._id
      });

      if (!note) {
        return res.status(404).json({ 
          error: 'Note not found'
        });
      }

      noteTitle = note.title;
      noteContent = note.content;
    }

    // Validation
    if (!noteContent || !noteContent.trim()) {
      return res.status(400).json({ 
        error: 'No content provided',
        detail: 'Please provide content or note_id'
      });
    }

    console.log(`[PDF] Generating PDF: ${noteTitle || 'Untitled'}`);

    // Create PDF
    const doc = new PDFDocument({
      margin: 50,
      size: 'A4'
    });

    // Set response headers
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${(noteTitle || 'notes').replace(/[^a-z0-9]/gi, '_')}.pdf"`);

    // Pipe PDF to response
    doc.pipe(res);

    // Add content
    doc.fontSize(20).text(noteTitle || 'Study Notes', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).text(`Generated by StudyAI Pro`, { align: 'center' });
    doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'center' });
    doc.moveDown(2);

    // Add main content
    doc.fontSize(12).text(noteContent, {
      align: 'left',
      lineGap: 5
    });

    // Finalize PDF
    doc.end();

    console.log(`[PDF] PDF generated successfully`);
  } catch (error) {
    console.error('[PDF] Error:', error);
    next(error);
  }
});

/**
 * @route   POST /output/email
 * @desc    Send notes via email
 * @access  Private
 */
router.post('/email', authenticate, async (req, res, next) => {
  try {
    const { note_id, to_email, title, content } = req.body;

    // Validation
    if (!to_email) {
      return res.status(400).json({ 
        error: 'Missing recipient email',
        detail: 'Please provide to_email'
      });
    }

    // Check if email is configured
    if (!config.smtpUser || !config.smtpPassword) {
      return res.status(503).json({ 
        error: 'Email service not configured',
        detail: 'SMTP credentials are not set up'
      });
    }

    let noteTitle = title;
    let noteContent = content;

    // If note_id provided, fetch from database
    if (note_id) {
      const note = await Note.findOne({
        _id: note_id,
        user_id: req.user._id
      });

      if (!note) {
        return res.status(404).json({ 
          error: 'Note not found'
        });
      }

      noteTitle = note.title;
      noteContent = note.content;
    }

    if (!noteContent) {
      return res.status(400).json({ 
        error: 'No content provided'
      });
    }

    console.log(`[EMAIL] Sending to: ${to_email}`);

    // Create transporter
    const transporter = nodemailer.createTransporter({
      host: config.smtpHost,
      port: config.smtpPort,
      secure: false,
      auth: {
        user: config.smtpUser,
        pass: config.smtpPassword
      }
    });

    // Send email
    const info = await transporter.sendMail({
      from: config.emailFrom || config.smtpUser,
      to: to_email,
      subject: noteTitle || 'Study Notes from StudyAI Pro',
      text: noteContent,
      html: `
        <h2>${noteTitle || 'Study Notes'}</h2>
        <p><em>Sent from StudyAI Pro by ${req.user.name}</em></p>
        <hr>
        <pre style="white-space: pre-wrap; font-family: Arial, sans-serif;">${noteContent}</pre>
        <hr>
        <p style="color: #666; font-size: 12px;">Generated on ${new Date().toLocaleString()}</p>
      `
    });

    console.log(`[EMAIL] Email sent: ${info.messageId}`);

    res.json({
      message: 'Email sent successfully',
      to: to_email,
      subject: noteTitle || 'Study Notes'
    });
  } catch (error) {
    console.error('[EMAIL] Error:', error);
    
    if (error.code === 'EAUTH') {
      return res.status(500).json({ 
        error: 'Email authentication failed',
        detail: 'Please check SMTP credentials'
      });
    }
    
    next(error);
  }
});

/**
 * @route   POST /output/whatsapp
 * @desc    Send notes via WhatsApp
 * @access  Private
 */
router.post('/whatsapp', authenticate, async (req, res, next) => {
  try {
    const { note_id, to_number, title, content } = req.body;

    // Validation
    if (!to_number) {
      return res.status(400).json({ 
        error: 'Missing recipient phone number',
        detail: 'Please provide to_number in format: whatsapp:+1234567890'
      });
    }

    // Check if Twilio is configured
    if (!config.twilioAccountSid || !config.twilioAuthToken) {
      return res.status(503).json({ 
        error: 'WhatsApp service not configured',
        detail: 'Twilio credentials are not set up'
      });
    }

    let noteTitle = title;
    let noteContent = content;

    // If note_id provided, fetch from database
    if (note_id) {
      const note = await Note.findOne({
        _id: note_id,
        user_id: req.user._id
      });

      if (!note) {
        return res.status(404).json({ 
          error: 'Note not found'
        });
      }

      noteTitle = note.title;
      noteContent = note.content;
    }

    if (!noteContent) {
      return res.status(400).json({ 
        error: 'No content provided'
      });
    }

    console.log(`[WHATSAPP] Sending to: ${to_number}`);

    // Initialize Twilio client
    const client = twilio(config.twilioAccountSid, config.twilioAuthToken);

    // Format message (WhatsApp has 1600 char limit)
    const messageHeader = `*${noteTitle || 'Study Notes'}*\n\nFrom StudyAI Pro\n\n`;
    const maxContentLength = 1500 - messageHeader.length;
    const truncatedContent = noteContent.length > maxContentLength 
      ? noteContent.substring(0, maxContentLength) + '...\n\n(Content truncated due to length)'
      : noteContent;

    const fullMessage = messageHeader + truncatedContent;

    // Send WhatsApp message
    const message = await client.messages.create({
      from: config.twilioWhatsappFrom,
      to: to_number.startsWith('whatsapp:') ? to_number : `whatsapp:${to_number}`,
      body: fullMessage
    });

    console.log(`[WHATSAPP] Message sent: ${message.sid}`);

    res.json({
      message: 'WhatsApp message sent successfully',
      to: to_number,
      message_sid: message.sid
    });
  } catch (error) {
    console.error('[WHATSAPP] Error:', error);
    
    if (error.code === 20003) {
      return res.status(500).json({ 
        error: 'Twilio authentication failed',
        detail: 'Please check Twilio credentials'
      });
    }
    
    next(error);
  }
});

/**
 * @route   POST /output/download
 * @desc    Prepare content for download (plain text)
 * @access  Private
 */
router.post('/download', authenticate, async (req, res, next) => {
  try {
    const { note_id, title, content, format = 'txt' } = req.body;

    let noteTitle = title;
    let noteContent = content;

    // If note_id provided, fetch from database
    if (note_id) {
      const note = await Note.findOne({
        _id: note_id,
        user_id: req.user._id
      });

      if (!note) {
        return res.status(404).json({ 
          error: 'Note not found'
        });
      }

      noteTitle = note.title;
      noteContent = note.content;
    }

    if (!noteContent) {
      return res.status(400).json({ 
        error: 'No content provided'
      });
    }

    const filename = (noteTitle || 'notes').replace(/[^a-z0-9]/gi, '_');

    if (format === 'txt') {
      res.setHeader('Content-Type', 'text/plain');
      res.setHeader('Content-Disposition', `attachment; filename="${filename}.txt"`);
      res.send(`${noteTitle || 'Study Notes'}\n${'='.repeat((noteTitle || 'Study Notes').length)}\n\nGenerated: ${new Date().toLocaleString()}\n\n${noteContent}`);
    } else if (format === 'md') {
      res.setHeader('Content-Type', 'text/markdown');
      res.setHeader('Content-Disposition', `attachment; filename="${filename}.md"`);
      res.send(`# ${noteTitle || 'Study Notes'}\n\n*Generated: ${new Date().toLocaleString()}*\n\n---\n\n${noteContent}`);
    } else {
      return res.status(400).json({ 
        error: 'Invalid format',
        detail: 'Format must be txt or md'
      });
    }

    console.log(`[DOWNLOAD] ${format.toUpperCase()} download prepared: ${filename}`);
  } catch (error) {
    console.error('[DOWNLOAD] Error:', error);
    next(error);
  }
});

export default router;
