import express from 'express';
import Note from '../models/Note.js';
import Flashcard from '../models/Flashcard.js';
import { authenticate } from '../middleware/auth.js';

const router = express.Router();

// Export note as Markdown
router.get('/note/:id/markdown', authenticate, async (req, res) => {
  try {
    const note = await Note.findOne({ _id: req.params.id, user_id: req.user._id });
    
    if (!note) {
      return res.status(404).json({ error: 'Note not found' });
    }

    const markdown = `# ${note.title}

**Created:** ${note.created_at.toLocaleDateString()}  
**Mode:** ${note.mode}

---

${note.content}

---

*Generated by StudyAI Pro*`;

    res.setHeader('Content-Type', 'text/markdown');
    res.setHeader('Content-Disposition', `attachment; filename="${note.title.replace(/[^a-z0-9]/gi, '_')}.md"`);
    res.send(markdown);

  } catch (error) {
    res.status(500).json({ error: 'Failed to export note' });
  }
});

// Export note as plain text
router.get('/note/:id/txt', authenticate, async (req, res) => {
  try {
    const note = await Note.findOne({ _id: req.params.id, user_id: req.user._id });
    
    if (!note) {
      return res.status(404).json({ error: 'Note not found' });
    }

    const text = `${note.title}\n\nCreated: ${note.created_at.toLocaleDateString()}\nMode: ${note.mode}\n\n${'-'.repeat(50)}\n\n${note.content}\n\n${'-'.repeat(50)}\n\nGenerated by StudyAI Pro`;

    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Content-Disposition', `attachment; filename="${note.title.replace(/[^a-z0-9]/gi, '_')}.txt"`);
    res.send(text);

  } catch (error) {
    res.status(500).json({ error: 'Failed to export note' });
  }
});

// Export flashcards as CSV
router.get('/flashcards/:id/csv', authenticate, async (req, res) => {
  try {
    const flashcard = await Flashcard.findOne({ _id: req.params.id, user_id: req.user._id });
    
    if (!flashcard) {
      return res.status(404).json({ error: 'Flashcard deck not found' });
    }

    let csv = 'Question,Answer,Difficulty,Times Reviewed,Confidence\n';
    
    flashcard.cards.forEach(card => {
      const question = `"${card.question.replace(/"/g, '""')}"`;
      const answer = `"${card.answer.replace(/"/g, '""')}"`;
      csv += `${question},${answer},${card.difficulty},${card.times_reviewed},${card.confidence}\n`;
    });

    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename="${flashcard.deck_name.replace(/[^a-z0-9]/gi, '_')}.csv"`);
    res.send(csv);

  } catch (error) {
    res.status(500).json({ error: 'Failed to export flashcards' });
  }
});

// Export flashcards as JSON (for Anki import)
router.get('/flashcards/:id/anki', authenticate, async (req, res) => {
  try {
    const flashcard = await Flashcard.findOne({ _id: req.params.id, user_id: req.user._id });
    
    if (!flashcard) {
      return res.status(404).json({ error: 'Flashcard deck not found' });
    }

    const ankiFormat = {
      __type__: "Deck",
      name: flashcard.deck_name,
      cards: flashcard.cards.map(card => ({
        Front: card.question,
        Back: card.answer,
        Tags: [card.difficulty]
      }))
    };

    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Content-Disposition', `attachment; filename="${flashcard.deck_name.replace(/[^a-z0-9]/gi, '_')}_anki.json"`);
    res.json(ankiFormat);

  } catch (error) {
    res.status(500).json({ error: 'Failed to export flashcards' });
  }
});

// Export all notes as combined PDF metadata (frontend will render PDF)
router.get('/notes/all', authenticate, async (req, res) => {
  try {
    const notes = await Note.find({ user_id: req.user._id })
      .sort({ created_at: -1 })
      .limit(100);

    res.json({
      export_type: 'notes_collection',
      total: notes.length,
      generated_at: new Date().toISOString(),
      notes: notes.map(note => ({
        title: note.title,
        content: note.content,
        mode: note.mode,
        created_at: note.created_at
      }))
    });

  } catch (error) {
    res.status(500).json({ error: 'Failed to export notes' });
  }
});

export default router;
